fix(provisioning): Add SSL protection configuration for UCS base
Add stunnel configuration to the APP to encrypt traffic between backups and primarys
with SSL. Add new package univention-provisioning-service-config to ship dependencies
and UCR files.
Issue univention/dev/projects/provisioning#113

diff --git a/apps/50provisioning-service-backup2master b/apps/50provisioning-service-backup2master
--- a/apps/50provisioning-service-backup2master
+++ b/apps/50provisioning-service-backup2master
@@ -21,6 +21,8 @@ LOG_DIR="/var/log/univention"
 SCRIPT_LOG="${LOG_DIR}/backup2master_and_${APP_NAME}_post.log"
 DRY_RUN="${DRY_RUN:-0}"
 
+eval "$(univention-config-registry shell)"
+
 exec > >(tee -a "$SCRIPT_LOG") 2>&1
 
 echo "=== $(date -Is) :: Starting UCS Backup->Master promotion + app reinitialize (${APP_NAME}) ==="
@@ -63,8 +65,8 @@ require_cmd univention-run-join-scripts
 # --- Check installed apps ---
 
 # --- Check APP_NAME is installed and backend not yet installed ---
-if ! univention-app info | grep -P '^(?=.*\bprovisioning-service=[^ ]+\b)(?!.*\bprovisioning-service-backend=[^ ]+\b).*' > /dev/null; then
-  echo "ERROR: App '${APP_NAME}' not installed or backend '${APP_BACKEND_NAME}' already installed." >&2
+if ! univention-app info | grep -P '^(?=.*\bprovisioning-service=[^ ]+\b).*' > /dev/null; then
+  echo "ERROR: App '${APP_NAME}' not installed." >&2
   exit 1
 fi
 
@@ -86,20 +88,23 @@ fi
 echo "Refreshing App Center cache..."
 run "univention-app update"
 
-# --- Install backend app ---
-run "univention-app install --noninteractive '${APP_BACKEND_NAME}' || {
-  echo 'ERROR: Failed to install backend app "${APP_BACKEND_NAME}".' >&2
-  exit 1
-}"
+# --- Listener activation ---
+echo "Activating ${APP_NAME} listener module"
+ucr unset listener/module/nubus-provisioning/deactivate
+ucr commit /etc/stunnel/univention-provisioning-stunnel.conf
+systemctl restart univention-directory-listener.service
+systemctl restart stunnel4.service
 
 # Reinitialize: this recreates the app container with current settings.
 # This is supported by the App Center and is commonly used by several UCS apps
 # to apply updated configuration. (See docs and forum references.)
+
 echo "Reinitializing ${APP_NAME}..."
 
 run "univention-app configure ${APP_NAME} --set provisioning-service/udm-rest-api-host=\"$ldap_master\" --set provisioning-service/primary=\"$ldap_master\""
 
-echo-warning "WARNING: Please update the following app settings on all other backups where the provisioning-service app is installed."
+echo-warning "WARNING: Please do the following on all other backups where the provisioning-service app is installed."
+echo-warning "    ucr commit /etc/stunnel/univention-provisioning-stunnel.conf; systemctl restart stunnel4.service"
 echo-warning "    univention-app configure ${APP_NAME} --set provisioning-service/udm-rest-api-host=<REPLACE_ME> --set provisioning-service/primary=<REPLACE_ME>"
 
 echo "=== $(date -Is) :: Completed. Log: ${SCRIPT_LOG} ==="
